# Generated by Django 2.2.4 on 2019-08-23 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_statusobj_applic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusobj',
            name='status',
        ),
        migrations.AlterField(
            model_name='statusobj',
            name='applic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='application.ApplicationObj'),
        ),
    ]
