# Generated by Django 2.2.4 on 2019-08-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20190823_0943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusObj',
        ),
    ]
