# Generated by Django 2.2.4 on 2019-08-23 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_delete_statusobj'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.ApplicationObj')),
            ],
        ),
    ]
