# Generated by Django 2.2.4 on 2019-08-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20190823_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationobj',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='StatusObj',
        ),
    ]
