# Generated by Django 2.2.4 on 2019-08-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20190823_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationobj',
            name='status',
        ),
    ]
